name: neural-stats
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - python=3.9.15
  - pip:
      - h5py==3.1.0
      - matplotlib==3.6.2
      - numpy==1.19.5
      - pandas==1.4.1
      - pillow==9.3.0
      - scikit-learn==1.1.3
      - scipy==1.9.3
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.5.0
      - tensorflow-addons==0.15.0
      - tensorflow-estimator==2.5.0
      - tensorflow-io-gcs-filesystem==0.28.0
      - tensorflow-probability==0.19.0

